[build]
  command = "sed -i 's/USE_NETLIFY_ENV/\\$GROQ_API_KEY/g' index.html && echo 'API key replaced'"
  publish = "."

[[headers]]
  for = "/*"
    [headers.values]
      X-Content-Type-Options = "nosniff"

[context.production.environment]
  GROQ_API_KEY = "$GROQ_API_KEY"

[context.deploy-preview.environment]
  GROQ_API_KEY = "$GROQ_API_KEY"

[context.branch-deploy.environment]
  GROQ_API_KEY = "$GROQ_API_KEY"

[context.dev.environment]
  GROQ_API_KEY = "$GROQ_API_KEY"
